2023-03-02 13:04:04,879 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Configure stats pid to 14440
2023-03-02 13:04:04,885 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-02 13:04:04,885 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-02 13:04:04,885 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-02 13:04:04,886 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-02 13:04:04,886 INFO    MainThread:14440 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_130404-leyfu1kl\logs\debug.log
2023-03-02 13:04:04,887 INFO    MainThread:14440 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_130404-leyfu1kl\logs\debug-internal.log
2023-03-02 13:04:04,887 INFO    MainThread:14440 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001EA75079F40>
2023-03-02 13:04:04,887 INFO    MainThread:14440 [wandb_init.py:init():532] calling init triggers
2023-03-02 13:04:04,887 INFO    MainThread:14440 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-02 13:04:04,888 INFO    MainThread:14440 [wandb_init.py:init():554] re-initializing run, found existing run on stack: yep0pvrx
2023-03-02 13:04:04,890 INFO    MainThread:14440 [wandb_run.py:_finish():1854] finishing run ananthu2014/ED22S015_DL_1/yep0pvrx
2023-03-02 13:04:04,890 INFO    MainThread:14440 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-02 13:04:04,890 INFO    MainThread:14440 [wandb_run.py:_restore():2066] restore
2023-03-02 13:04:04,890 INFO    MainThread:14440 [wandb_run.py:_restore():2072] restore done
2023-03-02 13:04:10,599 INFO    MainThread:14440 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-02 13:04:10,599 INFO    MainThread:14440 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-02 13:04:10,599 INFO    MainThread:14440 [wandb_run.py:_footer_sync_info():3398] logging synced files
2023-03-02 13:04:10,610 INFO    MainThread:14440 [wandb_init.py:init():588] starting backend
2023-03-02 13:04:10,610 INFO    MainThread:14440 [wandb_init.py:init():592] setting up manager
2023-03-02 13:04:10,614 INFO    MainThread:14440 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-02 13:04:10,617 INFO    MainThread:14440 [wandb_init.py:init():599] backend started and connected
2023-03-02 13:04:10,639 INFO    MainThread:14440 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-02 13:04:10,640 INFO    MainThread:14440 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-02 13:04:10,641 INFO    MainThread:14440 [wandb_init.py:init():687] updated telemetry
2023-03-02 13:04:10,702 INFO    MainThread:14440 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-02 13:04:12,270 INFO    MainThread:14440 [wandb_run.py:_on_init():2134] communicating current version
2023-03-02 13:04:12,349 INFO    MainThread:14440 [wandb_run.py:_on_init():2143] got version response 
2023-03-02 13:04:12,349 INFO    MainThread:14440 [wandb_init.py:init():775] starting run threads in backend
2023-03-02 13:04:27,302 INFO    MainThread:14440 [wandb_run.py:_console_start():2114] atexit reg
2023-03-02 13:04:27,302 INFO    MainThread:14440 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-02 13:04:27,302 INFO    MainThread:14440 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-02 13:04:27,302 INFO    MainThread:14440 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-02 13:04:27,302 INFO    MainThread:14440 [wandb_init.py:init():817] run started, returning control to user process
2023-03-02 13:04:27,642 ERROR   MainThread:14440 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:04:27,642 ERROR   MainThread:14440 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:04:27,691 INFO    MainThread:14440 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:04:27,691 INFO    MainThread:14440 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:05:19,017 INFO    MainThread:14440 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Configure stats pid to 14440
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_130519-80gmkbi7\logs\debug.log
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_130519-80gmkbi7\logs\debug-internal.log
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_init.py:init():532] calling init triggers
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_init.py:init():554] re-initializing run, found existing run on stack: leyfu1kl
2023-03-02 13:05:19,048 INFO    MainThread:14440 [wandb_run.py:_finish():1854] finishing run ananthu2014/ED22S015_DL_1/leyfu1kl
2023-03-02 13:05:19,055 INFO    MainThread:14440 [jupyter.py:save_history():449] not saving jupyter history
2023-03-02 13:05:19,055 INFO    MainThread:14440 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:05:19,055 INFO    MainThread:14440 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-02 13:05:19,055 INFO    MainThread:14440 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-02 13:05:19,055 INFO    MainThread:14440 [wandb_run.py:_restore():2066] restore
2023-03-02 13:05:19,055 INFO    MainThread:14440 [wandb_run.py:_restore():2072] restore done
2023-03-02 13:05:26,481 INFO    MainThread:14440 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-02 13:05:26,481 INFO    MainThread:14440 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-02 13:05:26,481 INFO    MainThread:14440 [wandb_run.py:_footer_sync_info():3398] logging synced files
