2023-03-02 14:39:48,992 INFO    MainThread:24920 [wandb_setup.py:_flush():68] Configure stats pid to 24920
2023-03-02 14:39:48,992 INFO    MainThread:24920 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-02 14:39:48,992 INFO    MainThread:24920 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-02 14:39:48,993 INFO    MainThread:24920 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'CS6910_ASSIGNMENT_1', 'entity': 'ananthu2014', 'root_dir': 'C:\\Users\\anant\\CS6910\\Assignment 1', 'run_id': 'nvrzckej', 'sweep_param_path': 'C:\\Users\\anant\\CS6910\\Assignment 1\\wandb\\sweep-6qodalfe\\config-nvrzckej.yaml', 'sweep_id': '6qodalfe'}
2023-03-02 14:39:48,993 INFO    MainThread:24920 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-02 14:39:48,993 INFO    MainThread:24920 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_143948-nvrzckej\logs\debug.log
2023-03-02 14:39:48,993 INFO    MainThread:24920 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_143948-nvrzckej\logs\debug-internal.log
2023-03-02 14:39:48,993 INFO    MainThread:24920 [wandb_init.py:init():532] calling init triggers
2023-03-02 14:39:48,994 INFO    MainThread:24920 [wandb_init.py:init():538] wandb.init called with sweep_config: {'activation': 'identity_function', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epochs': 40, 'lambd': 0.5, 'learning_rate': 0.001, 'loss': 'cross_entropy_function', 'momentum': 0.9, 'neurons': 128, 'num_hidden_layers': 5, 'optimizer': 'vanilla_gradient_descent', 'weight_init': 'random_initialization'}
config: {}
2023-03-02 14:39:48,994 INFO    MainThread:24920 [wandb_init.py:init():554] re-initializing run, found existing run on stack: nvrzckej
2023-03-02 14:39:48,995 INFO    MainThread:24920 [wandb_run.py:_finish():1854] finishing run ananthu2014/CS6910_ASSIGNMENT_1/nvrzckej
2023-03-02 14:39:48,996 INFO    MainThread:24920 [jupyter.py:save_history():449] not saving jupyter history
2023-03-02 14:39:48,996 INFO    MainThread:24920 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 14:39:48,996 INFO    MainThread:24920 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-02 14:39:48,996 INFO    MainThread:24920 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-02 14:39:48,996 INFO    MainThread:24920 [wandb_run.py:_restore():2066] restore
2023-03-02 14:39:48,996 INFO    MainThread:24920 [wandb_run.py:_restore():2072] restore done
2023-03-02 14:39:53,036 INFO    MainThread:24920 [wandb_init.py:init():588] starting backend
2023-03-02 14:39:53,037 INFO    MainThread:24920 [wandb_init.py:init():592] setting up manager
2023-03-02 14:39:53,059 INFO    MainThread:24920 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-02 14:39:53,074 INFO    MainThread:24920 [wandb_init.py:init():599] backend started and connected
2023-03-02 14:39:53,097 INFO    MainThread:24920 [wandb_run.py:_config_callback():1250] config_cb None None {'activation': 'identity_function', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epochs': 40, 'lambd': 0.5, 'learning_rate': 0.001, 'loss': 'cross_entropy_function', 'momentum': 0.9, 'neurons': 128, 'num_hidden_layers': 5, 'optimizer': 'vanilla_gradient_descent', 'weight_init': 'random_initialization'}
2023-03-02 14:39:53,098 INFO    MainThread:24920 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-02 14:39:53,098 INFO    MainThread:24920 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-02 14:39:53,098 INFO    MainThread:24920 [wandb_init.py:init():687] updated telemetry
2023-03-02 14:39:53,149 INFO    MainThread:24920 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-02 14:40:53,570 ERROR   MainThread:24920 [wandb_init.py:init():741] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-02 14:40:53,601 ERROR   MainThread:24920 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 759, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
