2023-03-07 12:20:02,330 INFO    MainThread:28084 [wandb_setup.py:_flush():68] Configure stats pid to 28084
2023-03-07 12:20:02,330 INFO    MainThread:28084 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-07 12:20:02,330 INFO    MainThread:28084 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-07 12:20:02,330 INFO    MainThread:28084 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-07 12:20:02,330 INFO    MainThread:28084 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-07 12:20:02,334 INFO    MainThread:28084 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230307_122002-zh2j7thr\logs\debug.log
2023-03-07 12:20:02,334 INFO    MainThread:28084 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230307_122002-zh2j7thr\logs\debug-internal.log
2023-03-07 12:20:02,335 INFO    MainThread:28084 [wandb_init.py:init():532] calling init triggers
2023-03-07 12:20:02,335 INFO    MainThread:28084 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-07 12:20:02,336 INFO    MainThread:28084 [wandb_init.py:init():554] re-initializing run, found existing run on stack: qfqkg9a8
2023-03-07 12:20:02,342 INFO    MainThread:28084 [wandb_run.py:_finish():1854] finishing run ananthu2014/CS6910_DL_ASS1/qfqkg9a8
2023-03-07 12:20:02,342 INFO    MainThread:28084 [jupyter.py:save_history():449] not saving jupyter history
2023-03-07 12:20:02,342 INFO    MainThread:28084 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-07 12:20:02,342 INFO    MainThread:28084 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-07 12:20:02,346 INFO    MainThread:28084 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-07 12:20:02,346 INFO    MainThread:28084 [wandb_run.py:_restore():2066] restore
2023-03-07 12:20:02,346 INFO    MainThread:28084 [wandb_run.py:_restore():2072] restore done
2023-03-07 12:20:35,595 INFO    MainThread:28084 [wandb_init.py:init():588] starting backend
2023-03-07 12:20:35,595 INFO    MainThread:28084 [wandb_init.py:init():592] setting up manager
2023-03-07 12:20:35,625 INFO    MainThread:28084 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-07 12:20:35,642 INFO    MainThread:28084 [wandb_init.py:init():599] backend started and connected
2023-03-07 12:20:35,817 INFO    MainThread:28084 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-07 12:20:35,817 INFO    MainThread:28084 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-07 12:20:35,817 INFO    MainThread:28084 [wandb_init.py:init():687] updated telemetry
2023-03-07 12:20:35,930 INFO    MainThread:28084 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-07 12:20:38,288 WARNING MsgRouterThr:28084 [router.py:message_loop():77] message_loop has been closed
2023-03-07 12:20:38,297 WARNING MsgRouterThr:28084 [router.py:message_loop():77] message_loop has been closed
2023-03-07 12:20:39,026 WARNING MainThread:28084 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 730, in init
    result = run_init_handle.wait(
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\anant\anaconda3\lib\threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\anant\anaconda3\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
