2023-03-05 00:25:28,898 INFO    StreamThr :20948 [internal.py:wandb_internal():87] W&B internal server running at pid: 20948, started at: 2023-03-05 00:25:28.897905
2023-03-05 00:25:28,901 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status
2023-03-05 00:25:28,944 INFO    WriterThread:20948 [datastore.py:open_for_write():85] open: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\run-nwbzx03r.wandb
2023-03-05 00:25:28,946 DEBUG   SenderThread:20948 [sender.py:send():336] send: header
2023-03-05 00:25:29,104 DEBUG   SenderThread:20948 [sender.py:send():336] send: run
2023-03-05 00:25:29,843 INFO    SenderThread:20948 [dir_watcher.py:__init__():216] watching files in: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files
2023-03-05 00:25:29,844 INFO    SenderThread:20948 [sender.py:_start_run_threads():1067] run started: nwbzx03r with start time 1677956128.907879
2023-03-05 00:25:29,844 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: summary_record
2023-03-05 00:25:29,845 INFO    SenderThread:20948 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-05 00:25:29,848 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: check_version
2023-03-05 00:25:29,849 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: check_version
2023-03-05 00:25:29,919 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: run_start
2023-03-05 00:25:30,859 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\wandb-summary.json
2023-03-05 00:25:30,930 DEBUG   HandlerThread:20948 [system_info.py:__init__():31] System info init
2023-03-05 00:25:30,930 DEBUG   HandlerThread:20948 [system_info.py:__init__():46] System info init done
2023-03-05 00:25:30,930 INFO    HandlerThread:20948 [system_monitor.py:start():151] Starting system monitor
2023-03-05 00:25:30,930 INFO    SystemMonitor:20948 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-03-05 00:25:30,930 INFO    HandlerThread:20948 [system_monitor.py:probe():172] Collecting system info
2023-03-05 00:25:30,935 INFO    SystemMonitor:20948 [interfaces.py:start():168] Started cpu
2023-03-05 00:25:30,935 INFO    SystemMonitor:20948 [interfaces.py:start():168] Started disk
2023-03-05 00:25:30,936 INFO    SystemMonitor:20948 [interfaces.py:start():168] Started gpu
2023-03-05 00:25:30,936 INFO    SystemMonitor:20948 [interfaces.py:start():168] Started memory
2023-03-05 00:25:30,953 INFO    SystemMonitor:20948 [interfaces.py:start():168] Started network
2023-03-05 00:25:30,964 DEBUG   HandlerThread:20948 [system_info.py:probe():195] Probing system
2023-03-05 00:25:30,966 DEBUG   HandlerThread:20948 [system_info.py:_probe_git():180] Probing git
2023-03-05 00:25:30,970 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:31,095 DEBUG   HandlerThread:20948 [system_info.py:_probe_git():188] Probing git done
2023-03-05 00:25:31,095 DEBUG   HandlerThread:20948 [system_info.py:probe():241] Probing system done
2023-03-05 00:25:31,095 DEBUG   HandlerThread:20948 [system_monitor.py:probe():181] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.9.13', 'heartbeatAt': '2023-03-04T18:55:30.964517', 'startedAt': '2023-03-04T18:55:28.864370', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': 'CS6910/Assignment 1/CS6910 Assignment 1.ipynb', 'root': 'C:/Users/anant/CS6910', 'git': {'remote': 'https://github.com/ananthu2014/CS6910.git', 'commit': '5f5c50e2285a1353056d5a4073970254484ba586'}, 'email': 'ananthu2014@gmail.com', 'host': 'ANANTHAKRISHNAN', 'username': 'anant', 'executable': 'C:\\Users\\anant\\anaconda3\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2400.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 2400.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'total': 117.99511337280273, 'used': 73.29241561889648}, 'gpu': 'NVIDIA GeForce GTX 1650', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650', 'memory_total': 4294967296}], 'memory': {'total': 7.883045196533203}}
2023-03-05 00:25:31,096 INFO    HandlerThread:20948 [system_monitor.py:probe():182] Finished collecting system info
2023-03-05 00:25:31,096 INFO    HandlerThread:20948 [system_monitor.py:probe():185] Publishing system info
2023-03-05 00:25:31,096 DEBUG   HandlerThread:20948 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-03-05 00:25:31,097 DEBUG   HandlerThread:20948 [system_info.py:_save_pip():67] Saving pip packages done
2023-03-05 00:25:31,097 DEBUG   HandlerThread:20948 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-03-05 00:25:31,873 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\requirements.txt
2023-03-05 00:25:31,873 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\conda-environment.yaml
2023-03-05 00:25:33,689 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:36,404 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:39,128 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:41,818 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:44,506 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:47,224 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:49,971 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:52,670 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:55,099 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\conda-environment.yaml
2023-03-05 00:25:55,335 DEBUG   HandlerThread:20948 [system_info.py:_save_conda():86] Saving conda packages done
2023-03-05 00:25:55,335 INFO    HandlerThread:20948 [system_monitor.py:probe():187] Finished publishing system info
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:55,361 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:25:55,361 DEBUG   SenderThread:20948 [sender.py:send():336] send: files
2023-03-05 00:25:55,361 INFO    SenderThread:20948 [sender.py:_save_file():1321] saving file wandb-metadata.json with policy now
2023-03-05 00:25:55,382 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: stop_status
2023-03-05 00:25:55,382 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: stop_status
2023-03-05 00:25:55,398 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:55,696 ERROR   Thread-16 :20948 [step_upload.py:_handle_event():141] Failed to upload file: C:\Users\anant\AppData\Local\Temp\tmpy5kyjrx7wandb\7jasrytt-wandb-metadata.json
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\apis\normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist ananthu2014/CS6910_DL_ASS1/nwbzx03r.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\filesync\step_upload.py", line 235, in run_and_notify
    job.run()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\filesync\upload_job.py", line 62, in run
    self.push()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\filesync\upload_job.py", line 113, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\apis\normalize.py", line 64, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\apis\normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 1769, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist ananthu2014/CS6910_DL_ASS1/nwbzx03r.
2023-03-05 00:25:55,696 DEBUG   SenderThread:20948 [sender.py:send():336] send: telemetry
2023-03-05 00:25:56,115 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\wandb-metadata.json
2023-03-05 00:25:56,115 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_created():275] file/dir created: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\output.log
2023-03-05 00:25:57,837 DEBUG   SenderThread:20948 [sender.py:send():336] send: telemetry
2023-03-05 00:25:57,837 DEBUG   SenderThread:20948 [sender.py:send():336] send: exit
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:send_exit():559] handling exit code: 1
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:send_exit():561] handling runtime: 27
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:send_exit():567] send defer
2023-03-05 00:25:57,837 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 0
2023-03-05 00:25:57,837 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 0
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 1
2023-03-05 00:25:57,837 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 1
2023-03-05 00:25:57,837 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 1
2023-03-05 00:25:57,837 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 2
2023-03-05 00:25:57,837 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 2
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [system_monitor.py:finish():161] Stopping system monitor
2023-03-05 00:25:57,837 DEBUG   SystemMonitor:20948 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-03-05 00:25:57,837 DEBUG   SystemMonitor:20948 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [interfaces.py:finish():175] Joined cpu
2023-03-05 00:25:57,837 DEBUG   SystemMonitor:20948 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-03-05 00:25:57,837 INFO    HandlerThread:20948 [interfaces.py:finish():175] Joined disk
2023-03-05 00:25:58,124 ERROR   gpu       :20948 [interfaces.py:monitor():129] Failed to sample metric: Not Supported
2023-03-05 00:25:58,171 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\wandb-summary.json
2023-03-05 00:25:58,171 INFO    HandlerThread:20948 [interfaces.py:finish():175] Joined gpu
2023-03-05 00:25:58,171 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\output.log
2023-03-05 00:25:58,171 INFO    HandlerThread:20948 [interfaces.py:finish():175] Joined memory
2023-03-05 00:25:58,171 INFO    HandlerThread:20948 [interfaces.py:finish():175] Joined network
2023-03-05 00:25:58,171 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:58,171 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 2
2023-03-05 00:25:58,171 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 3
2023-03-05 00:25:58,187 DEBUG   SenderThread:20948 [sender.py:send():336] send: stats
2023-03-05 00:25:58,187 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:58,188 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 3
2023-03-05 00:25:58,188 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:58,188 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 3
2023-03-05 00:25:58,189 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 4
2023-03-05 00:25:58,189 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:58,189 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 4
2023-03-05 00:25:58,189 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:58,190 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 4
2023-03-05 00:25:58,190 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 5
2023-03-05 00:25:58,191 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:58,191 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 5
2023-03-05 00:25:58,191 DEBUG   SenderThread:20948 [sender.py:send():336] send: summary
2023-03-05 00:25:58,191 INFO    SenderThread:20948 [sender.py:_save_file():1321] saving file wandb-summary.json with policy end
2023-03-05 00:25:58,191 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:58,191 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 5
2023-03-05 00:25:58,191 INFO    SenderThread:20948 [sender.py:transition_state():587] send defer: 6
2023-03-05 00:25:58,191 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: defer
2023-03-05 00:25:58,191 INFO    HandlerThread:20948 [handler.py:handle_request_defer():170] handle defer: 6
2023-03-05 00:25:58,191 DEBUG   SenderThread:20948 [sender.py:send_request():363] send_request: defer
2023-03-05 00:25:58,191 INFO    SenderThread:20948 [sender.py:send_request_defer():583] handle sender defer: 6
2023-03-05 00:25:58,191 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: status_report
2023-03-05 00:25:58,498 ERROR   SenderThread:20948 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-05 00:25:58,498 ERROR   SenderThread:20948 [internal_api.py:execute():246] {"errors":[{"message":"run ananthu2014/CS6910_DL_ASS1/nwbzx03r was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-05 00:25:58,864 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: poll_exit
2023-03-05 00:25:59,185 INFO    Thread-17 :20948 [dir_watcher.py:_on_file_modified():292] file/dir modified: C:\Users\anant\CS6910\Assignment 1\wandb\run-20230305_002528-nwbzx03r\files\wandb-summary.json
2023-03-05 00:25:59,868 ERROR   SenderThread:20948 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-05 00:25:59,868 ERROR   SenderThread:20948 [internal_api.py:execute():246] {"errors":[{"message":"run ananthu2014/CS6910_DL_ASS1/nwbzx03r was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-05 00:26:02,572 ERROR   SenderThread:20948 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-05 00:26:02,572 ERROR   SenderThread:20948 [internal_api.py:execute():246] {"errors":[{"message":"run ananthu2014/CS6910_DL_ASS1/nwbzx03r was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-05 00:26:02,572 INFO    SenderThread:20948 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 242, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 39, in execute
    request.raise_for_status()
  File "C:\Users\anant\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-03-05 00:26:03,884 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:26:07,011 ERROR   SenderThread:20948 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-05 00:26:07,011 ERROR   SenderThread:20948 [internal_api.py:execute():246] {"errors":[{"message":"run ananthu2014/CS6910_DL_ASS1/nwbzx03r was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-05 00:26:08,908 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:26:13,927 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:26:15,371 ERROR   SenderThread:20948 [internal_api.py:execute():245] 409 response executing GraphQL.
2023-03-05 00:26:15,371 ERROR   SenderThread:20948 [internal_api.py:execute():246] {"errors":[{"message":"run ananthu2014/CS6910_DL_ASS1/nwbzx03r was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-03-05 00:26:18,951 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:26:23,987 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
2023-03-05 00:26:29,028 DEBUG   HandlerThread:20948 [handler.py:handle_request():144] handle_request: keepalive
