2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Configure stats pid to 2660
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'CS6910_DL_ASS1', 'entity': 'ananthu2014', 'root_dir': 'C:\\Users\\anant\\CS6910\\Assignment 1', 'run_id': 'o6mzvgqh', 'sweep_param_path': 'C:\\Users\\anant\\CS6910\\Assignment 1\\wandb\\sweep-70xah3nu\\config-o6mzvgqh.yaml', 'sweep_id': '70xah3nu'}
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230308_053756-o6mzvgqh\logs\debug.log
2023-03-08 05:37:56,841 INFO    MainThread:2660 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230308_053756-o6mzvgqh\logs\debug-internal.log
2023-03-08 05:37:56,856 INFO    MainThread:2660 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000027B88EE11C0>
2023-03-08 05:37:56,856 INFO    MainThread:2660 [wandb_init.py:init():532] calling init triggers
2023-03-08 05:37:56,856 INFO    MainThread:2660 [wandb_init.py:init():538] wandb.init called with sweep_config: {'activation': 'relu_function', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.99, 'epochs': 40, 'lambd': 0, 'learning_rate': 0.001, 'loss': 'cross_entropy_function', 'momentum': 0.9, 'neurons': 64, 'num_hidden_layers': 1, 'optimizer': 'nadam', 'weight_init': 'random_initialization'}
config: {}
2023-03-08 05:37:56,856 INFO    MainThread:2660 [wandb_init.py:init():588] starting backend
2023-03-08 05:37:56,856 INFO    MainThread:2660 [wandb_init.py:init():592] setting up manager
2023-03-08 05:37:56,884 INFO    MainThread:2660 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-08 05:37:56,893 INFO    MainThread:2660 [wandb_init.py:init():599] backend started and connected
2023-03-08 05:37:56,916 INFO    MainThread:2660 [wandb_run.py:_config_callback():1250] config_cb None None {'activation': 'relu_function', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.99, 'epochs': 40, 'lambd': 0, 'learning_rate': 0.001, 'loss': 'cross_entropy_function', 'momentum': 0.9, 'neurons': 64, 'num_hidden_layers': 1, 'optimizer': 'nadam', 'weight_init': 'random_initialization'}
2023-03-08 05:37:56,916 INFO    MainThread:2660 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-08 05:37:56,916 INFO    MainThread:2660 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-08 05:37:56,916 INFO    MainThread:2660 [wandb_init.py:init():687] updated telemetry
2023-03-08 05:37:57,041 INFO    MainThread:2660 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-08 05:37:57,731 INFO    MainThread:2660 [wandb_run.py:_on_init():2134] communicating current version
2023-03-08 05:37:57,796 INFO    MainThread:2660 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-08 05:37:57,796 INFO    MainThread:2660 [wandb_init.py:init():775] starting run threads in backend
2023-03-08 05:38:19,014 INFO    MainThread:2660 [wandb_run.py:_console_start():2114] atexit reg
2023-03-08 05:38:19,014 INFO    MainThread:2660 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-08 05:38:19,014 INFO    MainThread:2660 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-08 05:38:19,014 INFO    MainThread:2660 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-08 05:38:19,029 INFO    MainThread:2660 [wandb_init.py:init():817] run started, returning control to user process
2023-03-08 05:38:19,048 INFO    MainThread:2660 [wandb_run.py:_config_callback():1250] config_cb ('_wandb', 'visualize', 'conf_mat') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': ''}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'conf_mat_table'}], 'fields': []}]}]}}} None
2023-03-08 05:38:20,045 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:38:20,045 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:43:55,339 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:43:55,347 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:43:55,348 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:44:02,174 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:44:02,179 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:44:02,179 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:44:27,429 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:44:27,642 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:44:27,642 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:44:37,003 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:44:37,008 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:44:37,008 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:45:01,170 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:45:01,174 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:45:01,175 INFO    MainThread:2660 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-08 05:46:14,160 INFO    MainThread:2660 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-08 05:46:14,201 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Configure stats pid to 2660
2023-03-08 05:46:14,202 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-08 05:46:14,202 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-08 05:46:14,202 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'CS6910_DL_ASS1', 'entity': 'ananthu2014', 'root_dir': 'C:\\Users\\anant\\CS6910\\Assignment 1', 'run_id': 'o6mzvgqh', 'sweep_param_path': 'C:\\Users\\anant\\CS6910\\Assignment 1\\wandb\\sweep-70xah3nu\\config-o6mzvgqh.yaml', 'sweep_id': '70xah3nu'}
2023-03-08 05:46:14,202 INFO    MainThread:2660 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-08 05:46:14,203 INFO    MainThread:2660 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230308_054614-o6mzvgqh\logs\debug.log
2023-03-08 05:46:14,203 INFO    MainThread:2660 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230308_054614-o6mzvgqh\logs\debug-internal.log
2023-03-08 05:46:14,204 INFO    MainThread:2660 [wandb_init.py:init():532] calling init triggers
2023-03-08 05:46:14,204 INFO    MainThread:2660 [wandb_init.py:init():538] wandb.init called with sweep_config: {'activation': 'relu_function', 'batch_size': 16, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.99, 'epochs': 40, 'lambd': 0, 'learning_rate': 0.001, 'loss': 'cross_entropy_function', 'momentum': 0.9, 'neurons': 64, 'num_hidden_layers': 1, 'optimizer': 'nadam', 'weight_init': 'random_initialization'}
config: {}
2023-03-08 05:46:14,204 INFO    MainThread:2660 [wandb_init.py:init():554] re-initializing run, found existing run on stack: o6mzvgqh
2023-03-08 05:46:14,206 INFO    MainThread:2660 [wandb_run.py:_finish():1854] finishing run ananthu2014/CS6910_DL_ASS1/o6mzvgqh
2023-03-08 05:46:14,209 INFO    MainThread:2660 [jupyter.py:save_history():449] not saving jupyter history
2023-03-08 05:46:14,209 INFO    MainThread:2660 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-08 05:46:14,209 INFO    MainThread:2660 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-08 05:46:14,209 INFO    MainThread:2660 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-08 05:46:14,209 INFO    MainThread:2660 [wandb_run.py:_restore():2066] restore
2023-03-08 05:46:14,209 INFO    MainThread:2660 [wandb_run.py:_restore():2072] restore done
2023-03-08 05:48:34,592 WARNING MsgRouterThr:2660 [router.py:message_loop():77] message_loop has been closed
2023-03-08 05:48:35,925 INFO    MainThread:2660 [wandb_run.py:_restore():2066] restore
2023-03-08 05:48:35,925 INFO    MainThread:2660 [wandb_run.py:_restore():2072] restore done
2023-03-08 05:48:36,020 ERROR   MainThread:2660 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 2092, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 2326, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 288, in wait
    on_probe(probe_handle)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 2291, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 567, in init
    self._wl._global_run_stack[-1].finish()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1845, in finish
    return self._finish(exit_code, quiet)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1860, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 2103, in _atexit_cleanup
    self._backend.cleanup()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\backend\backend.py", line 259, in cleanup
    self.interface.join()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 639, in join
    super().join()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 742, in join
    _ = self._communicate_shutdown()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 552, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\interface\router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
